# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foo < Formula
  desc "just me testing"
  homepage "https://becker.software"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v0.1.4/foo_0.1.4_Darwin_arm64.tar.gz"
      sha256 "043e16d9a61e6d39fa6d4e7037f7a5d88b2d9a2edf452e29d053976c41d6abc1"

      def install
        bin.install "foo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v0.1.4/foo_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "a6ba8c5e996796355bf789e7a593316406dad704a3cf424dc73d26a9c5630744"

      def install
        bin.install "foo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v0.1.4/foo_0.1.4_linux_x86_64.tar.gz"
      sha256 "420647ccc9d70a16eb534b8ff37f8073f2e913f984503239bc03463b28860368"

      def install
        bin.install "foo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v0.1.4/foo_0.1.4_linux_arm64.tar.gz"
      sha256 "93f5cb9fe8b33a80e848474c8aedb06ff292097297dbe1a5b36fa6ab1f0abbb1"

      def install
        bin.install "foo"
      end
    end
  end
end
