# This file was generated by GoReleaser. DO NOT EDIT.
cask "domain_exporter" do
  name "domain_exporter"
  desc "Exports the expiration time of your domains in the Prometheus format."
  homepage "https://github.com/caarlos0/domain_exporter"
  version "1.25.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "domain_exporter"

  on_macos do
    url "https://github.com/caarlos0/domain_exporter/releases/download/v#{version}/domain_exporter_#{version}_darwin_all.tar.gz",
        verified: "github.com/caarlos0/"
    sha256 "239546aa9979801f631c4143ba3e33e38892ade1bb69c5ef806192e36f26e329"
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/domain_exporter/releases/download/v#{version}/domain_exporter_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/"
      sha256 "be982cc3d7937efb8449f04711070a9c82639fc2aff62f400a7f867a8fd4a2a3"
    end
    on_arm do
      url "https://github.com/caarlos0/domain_exporter/releases/download/v#{version}/domain_exporter_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/"
      sha256 "51e355fee71fa164462bed8bb46b5bae7f55b298ec865dfba4dd25dbec410460"
    end
  end

  # No zap stanza required
end
