# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu" do
  name "emu"
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu"
  rename "emu*", "emu"

  on_macos do
    on_intel do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_amd64.tar.gz"
      sha256 "c14ab99e7d9ec5d8cffdf655694f97a5f819c30d1de14b9d4d51a4daec578ea3"
    end
    on_arm do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_arm64.tar.gz"
      sha256 "b3d37a9acd009716ccc33bd7a28d19f605ab7ecd5eb1a79f06e8f05502417524"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_amd64.tar.gz"
      sha256 "a579ad1313061106704e38ac8988e909c7f33b097b51a10e32a1bab35dd05804"
    end
    on_arm do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_arm64.tar.gz"
      sha256 "6a7d6165c0abed46627390bb94f6f3451bd0f433cd21c9c7f059c1b4aba8391f"
    end
  end

  postflight do
    # completions
    generate_completions_from_executable("emu", "completion")
    # manpages
    man_content = `./emu docs --format man-with-section`
    File.write("emu.1", man_content)
    man1.install "emu.1"
  end

  # No zap stanza required
end
