# This file was generated by GoReleaser. DO NOT EDIT.
cask "hevy" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "71beff44d16dfa15d87b11f685dcb826fb772a78a205a73ce67dcc51eda1a6e6"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Darwin_x86_64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
    on_arm do
      sha256 "e6ccfd0a71e1b404cba287524260d35a9e5ca7a0eba69b913da11863f944873d"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Darwin_arm64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bd09af864e6cee2c772cd6af50191e1b8100b8ee8c7892ca86a89feaee4616e"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Linux_x86_64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
    on_arm do
      sha256 "242a0f56a80c17ea238dd4a7e8cdae521159a752c89e99d226fa30acb1a29fd8"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Linux_arm64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
  end

  name "hevy"
  desc "CLI for managing Hevy routines via the public Hevy API"
  homepage "https://github.com/caarlos0/hevy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hevy"

  # No zap stanza required

end
