# This file was generated by GoReleaser. DO NOT EDIT.
cask "hevy" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "f739a5503456a1dd40d68c72cd4049afc90fba02ba707f455d04c877c1a601a4"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Darwin_x86_64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
    on_arm do
      sha256 "5d6b1f4f490dc7ae5ec736d10376cc5cf19b78f43cdff8ef5dbbe147d6d38416"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Darwin_arm64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2e07682da753d060894a50ea33d9ab4c9adcfb3dc6f700c36e8cde641372847"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Linux_x86_64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
    on_arm do
      sha256 "f1515d99a07d63ac15cb950c6929023cbe20590468c9d82bac13439a5e9a1107"
      url "https://github.com/caarlos0/hevy/releases/download/v#{version}/hevy_Linux_arm64.tar.gz",
        verified: "github.com/caarlos0/hevy"
    end
  end

  name "hevy"
  desc "CLI for managing Hevy routines via the public Hevy API"
  homepage "https://github.com/caarlos0/hevy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hevy"

  # No zap stanza required

end
