# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinata" do
  name "pinata"
  desc "GitHub Actions pinner."
  homepage "https://github.com/caarlos0/pinata"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinata"

  on_macos do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "f45fb26cd4c3acfe0c92aa8888c26b29475d18f18ca472a8c599af068fd63f81"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "6f185f50b746c5ac74d7e4343c9e1c97487dfe13549b9eba33af60b0bbcc2462"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "24b577ff4d1b4a6bdf3fe54bbb89ff77c5109c9ac9b4e25cf49a9dc33a37b3ad"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "749938732c90e2b756ed40c1bfef84632fc94da3bd98e25591a6dbfb30b88382"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinata"]
    end
  end

  # No zap stanza required
end
