# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinata" do
  name "pinata"
  desc "GitHub Actions pinner."
  homepage "https://github.com/caarlos0/pinata"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinata"

  on_macos do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "45bb46a2f16b4b2b72ed129d4d02fe94e87d778916ea915b16e304f61534a22a"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "0eb7d5b777aacc595f95ad41e9c7e06cb428e363713949c7c6d69ca8d02a163f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "5d83d13a68d85ed9645c9925ac003902190b99a4507ed8b5717646fa5997c5b7"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "0c0f09561369c31bbfd6c7df64b4af553c27cd7dea3d05b80da607ea844bcd81"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinata"]
    end
  end

  # No zap stanza required
end
