# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinata" do
  name "pinata"
  desc "GitHub Actions pinner."
  homepage "https://github.com/caarlos0/pinata"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinata"

  on_macos do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "2b9df320a62bb3c5f0455cd0f2d0374830db79057d1de01b52c98a094f942193"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "cbb63a591b294c2426af9d4637de358c8a8f1a801dc18e4eac0b8bc09ebf7971"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "89999811d738f07740e1459e6d2bc213dbaca3e2618ba4d81bf9593596c13cd2"
    end
    on_arm do
      url "https://github.com/caarlos0/pinata/releases/download/v#{version}/pinata_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/pinata"
      sha256 "77fb5948ddf8095955e4ea29f3292d4b84a0f38bf42c390b6567c5949c06a1ae"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinata"]
    end
  end

  # No zap stanza required
end
