# This file was generated by GoReleaser. DO NOT EDIT.
cask "prowl" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "02ea22389da56606c304071bc230afec417c0c82feac95ecaca1afc3c2a36f19"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c450208925d1471a331b104334c664ec5792cd7025b7248e6a52b9b54d986354"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0d83d14cc2300bdae53a66f60712b786cf97a09105dd4091839fdb66827dc07"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "80d00fff9d331951b5b4cc73ffeb6be8ade4a3710ffd0461d0e8cdd480c47b46"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_arm64.tar.gz"
    end
  end

  name "prowl"
  desc "A tiny terminal radar for your GitHub pull requests."
  homepage "https://github.com/caarlos0/prowl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prowl"

  # No zap stanza required

end
