# This file was generated by GoReleaser. DO NOT EDIT.
cask "prowl" do
  version "1.12.1"

  on_macos do
    on_arm do
      sha256 "17b9608893d840f7bb9723fbe20c597cb12adff8c8b664ceeb5fa7e1869f5060"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd9d8a2789638a414e8430d56cde3f2d89d8da6c5b562e3bf9aa3729bbc882bd"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f88eb93462ce34af2c7933458d232fd1c7f8ed9c395a6b36bc1e4aafd60fb82"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33a1719fb8a5185044550584cc21cedfddf3bbabea031cf04d6fb3e4fedf83ce"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_x86_64.tar.gz"
    end
  end

  name "prowl"
  desc "A tiny terminal radar for your GitHub pull requests."
  homepage "https://github.com/caarlos0/prowl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prowl"

  # No zap stanza required
end
