# This file was generated by GoReleaser. DO NOT EDIT.
cask "prowl" do
  version "1.13.1"

  on_macos do
    on_arm do
      sha256 "24b3b1cb0e2a27979afae20cfb4748e4971816e6d544b396ef781e1773df361b"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07cd123f0f05051f2a8fa5ada1b737fbd1b1839169271e1e714a139b961df49d"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "67ad89c4522eeabee18fc0c7bbee32a9fbfb9b749641173f83ec84732cb93dde"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37b2671424dafa2703728ea3b3b0fd04a32b506095b3ee52e0a088f6dbe0e1d1"
      url "https://github.com/caarlos0/prowl/releases/download/v#{version}/prowl_Linux_x86_64.tar.gz"
    end
  end

  name "prowl"
  desc "A tiny terminal radar for your GitHub pull requests."
  homepage "https://github.com/caarlos0/prowl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prowl"

  # No zap stanza required
end
