# This file was generated by GoReleaser. DO NOT EDIT.
cask "svu" do
  name "svu"
  desc "Semantic Version Utility"
  homepage "https://github.com/caarlos0/svu"
  version "3.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svu"
  manpage "manpages/svu.1.gz"
  bash_completion "completions/svu.bash"
  zsh_completion "completions/svu.zsh"
  fish_completion "completions/svu.fish"

  on_macos do
    url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_darwin_all.tar.gz",
        verified: "github.com/caarlos0/svu"
    sha256 "d32d3b793fae1ec86af6d8d423fc21a63dc1b17e531a2076cddb8630bded9f31"
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/svu"
      sha256 "3c093d9461b1875662df232319a314641b78ae78ddfec9378f572258803d699c"
    end
    on_arm do
      url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/svu"
      sha256 "8f00c170037bcdc1ba7f2b974ec5ac1b39da7457bebc985c5fd410c724e03bac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/svu"]
    end
  end

  # No zap stanza required
end
