# This file was generated by GoReleaser. DO NOT EDIT.
cask "svu" do
  name "svu"
  desc "Semantic Version Utility"
  homepage "https://github.com/caarlos0/svu"
  version "3.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svu"
  manpage "manpages/svu.1.gz"
  bash_completion "completions/svu.bash"
  zsh_completion "completions/svu.zsh"
  fish_completion "completions/svu.fish"

  on_macos do
    url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_darwin_all.tar.gz",
        verified: "github.com/caarlos0/svu"
    sha256 "ef1534a5e3eddef786a8b3ae0a280fc295662e3d3f738135ecb9f6477f7c4aab"
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_linux_amd64.tar.gz",
        verified: "github.com/caarlos0/svu"
      sha256 "f9fe4f0edb7d8cf4b0ecd84dd8ffa7e36186da6c701ab5fa59cb75a100a1705e"
    end
    on_arm do
      url "https://github.com/caarlos0/svu/releases/download/v#{version}/svu_#{version}_linux_arm64.tar.gz",
        verified: "github.com/caarlos0/svu"
      sha256 "ba8efd1da67532b811fe2864e43a93128b0c02702d1ad3a685ad58f41923f0eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/svu"]
    end
  end

  # No zap stanza required
end
