# This file was generated by GoReleaser. DO NOT EDIT.
cask "test" do
  version "1.14.46"

  on_macos do
    on_intel do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_amd64.zip"
      sha256 "ad9f8d21cc9498863395b60805704f1f1ebc2c417a2b0088334cdfc6214d84bd"
      rename "test_1.14.46_darwin_amd64/mybin", "mybin"
    end
    on_arm do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_arm64.zip"
      sha256 "6a5039e1df078af648863526dd10659706ff61f409a014134f89a05e037056e7"
      rename "test_1.14.46_darwin_arm64/mybin", "mybin"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_amd64.zip"
      sha256 "4598b100c02eb1696af8cd1d516eaec31c42a0d5e13d75f8590d07bc42db6917"
      rename "test_1.14.46_linux_amd64/mybin", "mybin"
    end
    on_arm do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_arm64.zip"
      sha256 "0f5ba7eac38ff5b0f8e76b17729068ce937dcaf001a16bd4988d90b01ddc005c"
      rename "test_1.14.46_linux_arm64/mybin", "mybin"
    end
  end

  name "test"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mybin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mybin"]
  end

  # No zap stanza required

  caveats <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
end
