# This file was generated by GoReleaser. DO NOT EDIT.
cask "test" do
  version "1.14.50"

  on_macos do
    on_intel do
      sha256 "3e29bc61e5f58d9e6303373ccef81a18172a1349e4acfa37007633e5b79c5d43"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_amd64.zip"
      rename "test_1.14.50_darwin_amd64/mybin", "mybin"
    end
    on_arm do
      sha256 "367346f1b237d9880c04d418d8b0e61858a321141783fb38f84d96970e164315"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_arm64.zip"
      rename "test_1.14.50_darwin_arm64/mybin", "mybin"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ef0ab3fe727bb2ccc3f0a87d11d5851205525ea0d18f8ff5df38e8b955f72fe"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_amd64.zip"
      rename "test_1.14.50_linux_amd64/mybin", "mybin"
    end
    on_arm do
      sha256 "ed10845d597cf0919591f6a25b7fd5a1ee1173875edc331068945fdc86d7d34f"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_arm64.zip"
      rename "test_1.14.50_linux_arm64/mybin", "mybin"
    end
  end

  name "test"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mybin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mybin"]
  end

  # No zap stanza required

  caveats <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
end
