# This file was generated by GoReleaser. DO NOT EDIT.
cask "test" do
  version "1.14.51"

  on_macos do
    on_intel do
      sha256 "034f06c3c5f74e4e4bdb35308ae5aa5cb3fc04add43c8b5c48ce5e1a177c380f"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_amd64.zip"
      rename "test_1.14.51_darwin_amd64/mybin", "mybin"
    end
    on_arm do
      sha256 "c90736d494f8fbdafad8f8ce0264891a27ff77df87362d887d2a86778c033401"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_darwin_arm64.zip"
      rename "test_1.14.51_darwin_arm64/mybin", "mybin"
    end
  end

  on_linux do
    on_intel do
      sha256 "de43c4d17b830e205ab146df7cb223d224160c8a06f0b5b0715477e734158a81"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_amd64.zip"
      rename "test_1.14.51_linux_amd64/mybin", "mybin"
    end
    on_arm do
      sha256 "e6027d428e689b34d993ac931e620242b425af1bfe1b066f7988db999586a4c5"
      url "https://github.com/caarlos0-graveyard/test/releases/download/v#{version}/test_#{version}_linux_arm64.zip"
      rename "test_1.14.51_linux_arm64/mybin", "mybin"
    end
  end

  name "test"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mybin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mybin"]
  end

  # No zap stanza required

  caveats <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
end
