# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttop" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2207b0b16f36bb927b4a85cde7992129bab97bfe49de215fa7904df7578d3ba3"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fb94a83c2d071b695b8e1aeb5fa89a238c879f261f96cfeacffc460fbcc3a7d5"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17da55e6f2065ed551c7bc6904328aaec46e048d590f9b3eb68c8ffe1b689fef"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f3403ca8ac00d708de71be856b0bc762432369540a12bef927533d86fae566b0"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Linux_arm64.tar.gz"
    end
  end

  name "ttop"
  desc "A tiny TUI that lists, filters and kills the processes running in every tmux pane."
  homepage "https://github.com/caarlos0/ttop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttop"

  # No zap stanza required

end
