# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttop" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0acc57485f9ea20d484514056b804de4084ed46953286c5c9cb0da948ea9365b"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b17d876402c580816cb3f3c3324b7f80099200fca40d02f0d507cac816dbe554"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ce674c6d17299348f7539c732c591d5042a27d3b13c36576d2052b0c246da68"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "983da4da38c21b11298097aaf6abab1abd8e5c48ec4f9dfcb7ba5f643f59070f"
      url "https://github.com/caarlos0/ttop/releases/download/v#{version}/ttop_Linux_arm64.tar.gz"
    end
  end

  name "ttop"
  desc "A tiny TUI that lists, filters and kills the processes running in every tmux pane."
  homepage "https://github.com/caarlos0/ttop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttop"

  # No zap stanza required

end
