# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aaaaaaaaa < Formula
  desc ""
  homepage ""
  version "0.5.4"

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v0.5.4/aaaaaaaaa_0.5.4_darwin_amd64.tar.gz"
    sha256 "6fbd1e4490a15dcb30efd0489e323b7a22f4ce1da2906366d5ee6ae95c73655f"

    def install
      bin.install "bar"
      bin.install "foo"
      bin.install "moises"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Aaaaaaaaa
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v0.5.4/aaaaaaaaa_0.5.4_linux_amd64.tar.gz"
      sha256 "12184592a8cb593a8d7fbf42d3ee3600fdc96ece80317f82d49a5ee700088b07"

      def install
        bin.install "bar"
        bin.install "foo"
        bin.install "moises"
      end
    end
  end

  def caveats
    <<~EOS
      Test formula, dont use it. It doesnt do anything
    EOS
  end

  test do
    system "#{bin}/foo"
    system "#{bin}/moises"
  end
end
