# This file was generated by GoReleaser. DO NOT EDIT.
class Act < Formula
  desc "Run GitHub Actions locally"
  homepage "https://github.com/nektos/act"
  url "https://github.com/caarlos0/act/releases/download/v0.2.0/act_Darwin_x86_64.tar.gz"
  version "0.2.0"
  sha256 "566be4bbdfd5b121fa8930905b4cd8b3807762e735e0fac752537c5425a86648"

  def install
    bin.install "act"
  end

  test do
    system "#{bin}/act --version"
  end
end
