# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloneOrg < Formula
  desc "Clone all repos of a GitHub user or organization"
  homepage "https://github.com/caarlos0/clone-org"
  version "1.5.0"

  on_macos do
    url "https://github.com/caarlos0/clone-org/releases/download/v1.5.0/clone-org_1.5.0_darwin_all.tar.gz"
    sha256 "348e326bb05a1049b1ada7eafe476b4ab9cd62ddb63d01f074d3fb4005043dcb"

    def install
      bin.install "clone-org"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/clone-org/releases/download/v1.5.0/clone-org_1.5.0_linux_arm64.tar.gz"
      sha256 "508ab541ca3cc2d257d4797a436c1d0be13d191d9b2f926376ac9f9a20032122"

      def install
        bin.install "clone-org"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/clone-org/releases/download/v1.5.0/clone-org_1.5.0_linux_amd64.tar.gz"
      sha256 "82f63c0afb6be5678bcb815da98a6bb03a0f51415436f4255098ffa1a3f5aa52"

      def install
        bin.install "clone-org"
      end
    end
  end
end
