# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiscordApplemusicRichPresence < Formula
  desc "Apple Music Rich Presence for Discord"
  homepage "https://caarlos0.dev"
  version "0.3.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/discord-applemusic-rich-presence/releases/download/v0.3.0/discord-applemusic-rich-presence_0.3.0_darwin_arm64.tar.gz"
      sha256 "65ae8d5a8a38773ce5a00629d576967b2ec661fa25009e4ec94f6c06cecd362d"

      def install
        bin.install "discord-applemusic-rich-presence"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/discord-applemusic-rich-presence/releases/download/v0.3.0/discord-applemusic-rich-presence_0.3.0_darwin_amd64.tar.gz"
      sha256 "9d97042c3295d2cce3a8961a6470f324828c5b1107cb8b0b6b91059e9b66e67f"

      def install
        bin.install "discord-applemusic-rich-presence"
      end
    end
  end

  service do
    run [opt_bin/"discord-applemusic-rich-presence"]
    keep_alive true
    log_path var/"log/discord-applemusic-rich-presence.log"
    error_log_path var/"log/discord-applemusic-rich-presence.log"
  end
end
