# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DiscordApplemusicRichPresence < Formula
  desc "Apple Music Rich Presence for Discord"
  homepage "https://caarlos0.dev"
  version "0.2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/discord-applemusic-rich-presence/releases/download/v0.2.0/discord-applemusic-rich-presence_0.2.0_darwin_arm64.tar.gz"
      sha256 "8ce43028d78b343f2bcad8ddefbfeb8fba72c7a1a26840cfe40c18345e65067e"

      def install
        bin.install "discord-applemusic-rich-presence"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/discord-applemusic-rich-presence/releases/download/v0.2.0/discord-applemusic-rich-presence_0.2.0_darwin_amd64.tar.gz"
      sha256 "edfe3160ed8dc48371934f7d75fdf1592fc51431900183d9496ec9daff3aaaee"

      def install
        bin.install "discord-applemusic-rich-presence"
      end
    end
  end

  service do
    run [opt_bin/"discord-applemusic-rich-presence"]
    keep_alive true
    log_path var/"log/discord-applemusic-rich-presence.log"
    error_log_path var/"log/discord-applemusic-rich-presence.log"
  end
end
