# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DomainExporter < Formula
  desc "Exports the expiration time of your domains in the Prometheus format."
  homepage "https://github.com/caarlos0/domain_exporter"
  version "1.15.0"

  on_macos do
    url "https://github.com/caarlos0/domain_exporter/releases/download/v1.15.0/domain_exporter_1.15.0_darwin_all.tar.gz"
    sha256 "f6188bbf10c82540736a8e135cc2d5ec4b84db160b933c904982999914e4b210"

    def install
      bin.install "domain_exporter"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/domain_exporter/releases/download/v1.15.0/domain_exporter_1.15.0_linux_arm64.tar.gz"
      sha256 "336924360ee3aeabb94c365a5d69d112e815208dcb5c6c8101889d66ad2434e5"

      def install
        bin.install "domain_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/domain_exporter/releases/download/v1.15.0/domain_exporter_1.15.0_linux_amd64.tar.gz"
      sha256 "1c1eb7c977cc79a7841ffbd2b89985d3f0ef299ae4dd648f54467ee5aa438fc2"

      def install
        bin.install "domain_exporter"
      end
    end
  end
end
