# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DomainExporter < Formula
  desc "Exports the expiration time of your domains in the Prometheus format."
  homepage "https://github.com/caarlos0/domain_exporter"
  version "1.21.1"

  on_macos do
    url "https://github.com/caarlos0/domain_exporter/releases/download/v1.21.1/domain_exporter_1.21.1_darwin_all.tar.gz"
    sha256 "abcf94516029e63dbdc6d6a07246211b5ee054e41957ad89247b51703b39fc64"

    def install
      bin.install "domain_exporter"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/domain_exporter/releases/download/v1.21.1/domain_exporter_1.21.1_linux_arm64.tar.gz"
      sha256 "ddcb441e8240d21fbeb9b4de4fa44f263761c7d8777dff5bee1c8bbd30f7e78e"

      def install
        bin.install "domain_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/domain_exporter/releases/download/v1.21.1/domain_exporter_1.21.1_linux_amd64.tar.gz"
      sha256 "3a5c2283bc5e11bfcc90ac19a93277c84eacfca0076792e13fac8b6cd239fa7a"

      def install
        bin.install "domain_exporter"
      end
    end
  end
end
