# This file was generated by GoReleaser. DO NOT EDIT.
class DomainExporter < Formula
  desc ""
  homepage ""
  url "https://github.com/caarlos0/domain_exporter/releases/download/v1.4.0/domain_exporter_darwin_amd64.tar.gz"
  version "1.4.0"
  sha256 "cb50174b73c751e8bf2f88c71d48fd6a3a6c0bba3612aac04abf007a3f2a749f"

  def install
    bin.install "domain_exporter"
  end
end
