# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EsSnapHangingNodes < Formula
  desc "Find nodes hanging an ElasticSearch snapshot."
  homepage "https://github.com/caarlos0/es-snap-hanging-nodes"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/es-snap-hanging-nodes/releases/download/v0.1.0/es-snap-hanging-nodes_0.1.0_darwin_amd64.tar.gz"
    sha256 "de22efffb1ebc85aa03ce905c716922a479e982d41232f25f47a353afcd7af38"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/es-snap-hanging-nodes/releases/download/v0.1.0/es-snap-hanging-nodes_0.1.0_linux_amd64.tar.gz"
    sha256 "4aebb83c3f6571a7abfbc4507a9abbef70a760919b294054538a374fea42f0db"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/es-snap-hanging-nodes/releases/download/v0.1.0/es-snap-hanging-nodes_0.1.0_linux_arm64.tar.gz"
    sha256 "8154e18b81354b4c03eeb28146c4fbafcde937cb14acec13f8f460df34454cd6"
  end

  def install
    bin.install "es-snap-hanging-nodes"
  end
end
