# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FastcomExporter < Formula
  desc "Exports Fast.com results to the Prometheus format"
  homepage "https://github.com/caarlos0/fastcom-exporter"
  version "1.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/fastcom-exporter/releases/download/v1.3.0/fastcom-exporter_1.3.0_darwin_amd64.tar.gz"
      sha256 "31b26feb568c535d83a30b000c5167060527c204d871bf0295448a75e861ae6b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/fastcom-exporter/releases/download/v1.3.0/fastcom-exporter_1.3.0_darwin_arm64.tar.gz"
      sha256 "d31e48604d418faa26cb147526af34e70b5b4daa906c5664e2fc50cefc35a87f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/fastcom-exporter/releases/download/v1.3.0/fastcom-exporter_1.3.0_linux_amd64.tar.gz"
      sha256 "497caad759fcf3e623571307d6287de40319c229e7d121636b50cab609bce800"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/fastcom-exporter/releases/download/v1.3.0/fastcom-exporter_1.3.0_linux_arm64.tar.gz"
      sha256 "52d544012ff240e054e35b4c804d186c9ea3af5b0b5cf2a16df421d59ab39263"
    end
  end

  def install
    bin.install "fastcom-exporter"
  end
end
