# This file was generated by GoReleaser. DO NOT EDIT.
class ForkCleaner < Formula
  desc "Cleans up old and inactive forks on your github account."
  homepage "https://github.com/caarlos0/fork-cleaner"
  version "1.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/fork-cleaner/releases/download/v1.5.0/fork-cleaner_1.5.0_darwin_amd64.tar.gz"
    sha256 "022d7a476fc9425a1f31637cb6b267c808424fc45e144a06a230cdc91001a7fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/fork-cleaner/releases/download/v1.5.0/fork-cleaner_1.5.0_linux_amd64.tar.gz"
      sha256 "a620bdf95059fced7fdb2eee8fa221c50c87c001b647a145d509d737060d3ebd"
    end
  end

  def install
    bin.install "fork-cleaner"
  end
end
