# This file was generated by GoReleaser. DO NOT EDIT.
class ForkCleaner < Formula
  desc "Cleans up old and inactive forks on your github account."
  homepage "https://github.com/caarlos0/fork-cleaner"
  version "1.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/fork-cleaner/releases/download/v1.6.1/fork-cleaner_1.6.1_darwin_amd64.tar.gz"
    sha256 "dda0f0b40393923f27675c50c0cb49967b7cf530d37bf1fe42fd84fb315f7ebe"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/fork-cleaner/releases/download/v1.6.1/fork-cleaner_1.6.1_linux_amd64.tar.gz"
      sha256 "0da9889a7b73df826185e2bc1f8aa1c3a3a2fb5e77a943a664a9829cb0570f64"
    end
  end

  def install
    bin.install "fork-cleaner"
  end
end
