# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubReleasesExporter < Formula
  desc "Exports GitHub release metrics to the Prometheus format"
  homepage ""
  version "1.6.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.6.0/github_releases_exporter_darwin_amd64.tar.gz"
    sha256 "45582654bf51a88742bf40db92d8d9d7f1c71320f99b4a24e8645d7700bb83ae"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.6.0/github_releases_exporter_darwin_arm64.tar.gz"
    sha256 "61495b265cc9c62a9c944ddf6ba5497fdb21f74d48b7a321de7c91119b65cd2d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.6.0/github_releases_exporter_linux_amd64.tar.gz"
    sha256 "1631d0486ccc262dd9564c9c603a215f1d6df05bd55148fe5bee33953d90ada5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.6.0/github_releases_exporter_linux_arm64.tar.gz"
    sha256 "5660e6ff4d0446942154200756b170e9ea9b73bca61878ead92335214683a481"
  end

  def install
    bin.install "github_releases_exporter"
  end
end
