# This file was generated by GoReleaser. DO NOT EDIT.
class GithubReleasesExporter < Formula
  desc ""
  homepage ""
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.4.0/github_releases_exporter_darwin_amd64.tar.gz"
    sha256 "3759721d36ed90b982136b9faac1480bbb246ca7cd37a77f7d27b8980d7e7dcd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/github_releases_exporter/releases/download/v1.4.0/github_releases_exporter_linux_amd64.tar.gz"
    sha256 "1bffe07c5673cb14c97328cef2bbbd9fc58013e9ae8438534780ce5af7a9510a"
  end

  def install
    bin.install "github_releases_exporter"
  end
end
