# This file was generated by GoReleaser. DO NOT EDIT.
class Jsonfmt < Formula
  desc "Like gofmt, but for JSON files"
  homepage "https://carlosbecker.com"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/jsonfmt/releases/download/v0.2.2/jsonfmt_0.2.2_darwin_amd64.tar.gz"
    sha256 "949365d7fb2b54bf2560e3c308c216d3a1fd042209071573975ed822a1a3217d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/jsonfmt/releases/download/v0.2.2/jsonfmt_0.2.2_linux_amd64.tar.gz"
      sha256 "40fbc8196260bdd352aabaef15bdcf4bf9946498ec895c4278191e4412051ca0"
    end
  end

  def install
    bin.install "jsonfmt"
  end

  test do
    system "#{bin}/gofmt -v"
  end
end
