# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectx < Formula
  desc "kubectx and kubens are power tools for kubectl"
  homepage "https://kubectx.dev"
  version "0.9.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_darwin_x86_64.tar.gz"
    sha256 "df24c1552d9109f03b316f55350447d03d17ff85905e78a9eac9de63c39a6f71"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
      sha256 "2e98229dbeb9663b969e2ddd8dd3309220a9059c3915215f5cffba68a5db40be"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_arm64.tar.gz"
        sha256 "a3b3aa6d79a98012348e4ea344e945d9b33bbd44f980ef3d440d91c0239a659e"
      else
        url "https://github.com/caarlos0/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_armhf.tar.gz"
        sha256 "fff4560b6d5d585f9fa627bf1ed94ddd15ae8a3d79902fe967f9be2d111fb4e9"
      end
    end
  end

  def install
    bin.install "kubens"
    bin.install "kubectx"
    bash_completion.install "completion/kubectx.bash" => "kubectx"
    bash_completion.install "completion/kubens.bash" => "kubens"
    zsh_completion.install "completion/kubectx.zsh" => "_kubectx"
    zsh_completion.install "completion/kubens.zsh" => "_kubens"
    fish_completion.install "completion/kubectx.fish"
    fish_completion.install "completion/kubens.fish"
  end
end
