# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectx < Formula
  desc "kubectx and kubens are power tools for kubectl"
  homepage "https://kubectx.dev"
  version "0.10.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.1/kubectx_v0.10.1_darwin_amd64.tar.gz"
      sha256 "566262c5009bd305fcf852d475964a8c56ad72cc065b5c6e2e7928dfef2b02e0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.1/kubectx_v0.10.1_darwin_arm64.tar.gz"
      sha256 "b0196851c196533d4235fcac246f98e60eb2369fcf876d06da9a967af245ab6e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.1/kubectx_v0.10.1_linux_amd64.tar.gz"
      sha256 "8eba3a77a958fbb74c1eae136ccd64b91bb2870e957a33d4c611d9e730f0689c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.1/kubectx_v0.10.1_linux_arm64.tar.gz"
      sha256 "4f0d3d7ac3a240354c43080b5f5c1d695d7e2e96f72fcb2afc88c4b6e1181d0a"
    end
  end

  def install
    bin.install "kubens"
    bin.install "kubectx"
    bash_completion.install "completion/kubectx.bash" => "kubectx"
    bash_completion.install "completion/kubens.bash" => "kubens"
    zsh_completion.install "completion/kubectx.zsh" => "_kubectx"
    zsh_completion.install "completion/kubens.zsh" => "_kubens"
    fish_completion.install "completion/kubectx.fish"
    fish_completion.install "completion/kubens.fish"
  end
end
