# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectx < Formula
  desc "kubectx and kubens are power tools for kubectl"
  homepage "https://kubectx.dev"
  version "0.10.2"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.2/kubectx_v0.10.2_darwin_amd64.tar.gz"
      sha256 "ac323ca07f03596c68c53f7f842f9d1954f0e2fc2ff9482105e79f2571985368"
    end
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/kubectx/releases/download/v0.10.2/kubectx_v0.10.2_darwin_arm64.tar.gz"
      sha256 "1b3f0bed28d586849b675daf04e31fdfab00b780fc20e56c70e24aa6a87c88d8"
    end
  end

  def install
    bin.install "kubens"
    bin.install "kubectx"
    bash_completion.install "completion/kubectx.bash" => "kubectx"
    bash_completion.install "completion/kubens.bash" => "kubens"
    zsh_completion.install "completion/kubectx.zsh" => "_kubectx"
    zsh_completion.install "completion/kubens.zsh" => "_kubens"
    fish_completion.install "completion/kubectx.fish"
    fish_completion.install "completion/kubens.fish"
  end
end
