# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtree < Formula
  desc "Convert markdown lists into beautiful ASCII trees"
  homepage "https://github.com/caarlos0/mdtree"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/caarlos0/mdtree/releases/download/v0.1.1/mdtree_0.1.1_darwin_all.tar.gz"
    sha256 "a94da40f7957149d5377ac69ed866c0223b744408e189939ec4631dab871424c"

    def install
      bin.install "mdtree"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/mdtree/releases/download/v0.1.1/mdtree_0.1.1_linux_amd64.tar.gz"
        sha256 "518e2f26dec0698a6429b2cdbbbb859aab06b55b06d9b7d6cfd4dcd1db981da2"

        def install
          bin.install "mdtree"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/mdtree/releases/download/v0.1.1/mdtree_0.1.1_linux_arm64.tar.gz"
        sha256 "fd8681c8a597e78212b1a57a813d3f229a6ebb058d20664e5c338cdd6e335d8b"

        def install
          bin.install "mdtree"
        end
      end
    end
  end
end
