# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtree < Formula
  desc "Convert markdown lists into beautiful ASCII trees"
  homepage "https://github.com/caarlos0/mdtree"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/caarlos0/mdtree/releases/download/v0.1.0/mdtree_0.1.0_darwin_all.tar.gz"
    sha256 "4974e308784e6d7d5e9d51b7857eaa5e763949b1c0c55de164715a46836e531f"

    def install
      bin.install "mdtree"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/mdtree/releases/download/v0.1.0/mdtree_0.1.0_linux_amd64.tar.gz"
        sha256 "d0d26aa89305cdb6bc7a547467c586de684bcd34213f03f1596773981f7a44e5"

        def install
          bin.install "mdtree"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/mdtree/releases/download/v0.1.0/mdtree_0.1.0_linux_arm64.tar.gz"
        sha256 "4e0ed4f0537c34b9560b4e0fee9529d113b01c8b04199cedf97013b6b94c56ca"

        def install
          bin.install "mdtree"
        end
      end
    end
  end
end
