# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrgStats < Formula
  desc "Get the contributor stats summary from all repositories of any given organization"
  homepage "https://github.com/caarlos0/org-stats"
  version "1.11.0"

  on_macos do
    url "https://github.com/caarlos0/org-stats/releases/download/v1.11.0/org-stats_darwin_all.tar.gz"
    sha256 "f07cf9d25dc744943c93bd529aa4fae1dfe6da65e2c79bbeb35b871120e40488"

    def install
      bin.install "org-stats"
      bash_completion.install "completions/org-stats.bash" => "org-stats"
      zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
      fish_completion.install "completions/org-stats.fish"
      man1.install "manpages/org-stats.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.11.0/org-stats_linux_arm64.tar.gz"
      sha256 "a9b20e20465af64ebfbffc391387bcb4d46d8e6b40e666f171b3f68b496c2618"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
        man1.install "manpages/org-stats.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.11.0/org-stats_linux_amd64.tar.gz"
      sha256 "17f67925cfbff11999329dd0b2e55a738adbfbb12cf1abe2fe8b0fb968781dca"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
        man1.install "manpages/org-stats.1.gz"
      end
    end
  end
end
