# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrgStats < Formula
  desc "Get the contributor stats summary from all repos of any given organization"
  homepage "https://github.com/caarlos0/org-stats"
  version "1.10.0"

  on_macos do
    url "https://github.com/caarlos0/org-stats/releases/download/v1.10.0/org-stats_darwin_all.tar.gz"
    sha256 "9c7243f4e86b26c962a90ab432f2e2c9221926ce713af362f2850767e7d79e39"

    def install
      bin.install "org-stats"
      bash_completion.install "completions/org-stats.bash" => "org-stats"
      zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
      fish_completion.install "completions/org-stats.fish"
      man1.install "manpages/org-stats.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.10.0/org-stats_linux_arm64.tar.gz"
      sha256 "14045466879d299ab5a65f00a376967715a75e2c33fe7690e994b586d6360d5f"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
        man1.install "manpages/org-stats.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.10.0/org-stats_linux_amd64.tar.gz"
      sha256 "e0e3978f94e93fae8a8c0d3fd3ed6b7816e356497de2b62befa5d69cb240fedc"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
        man1.install "manpages/org-stats.1.gz"
      end
    end
  end
end
