# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrgStats < Formula
  desc "Get the contributor stats summary from all repos of any given organization"
  homepage "https://github.com/caarlos0/org-stats"
  version "1.9.0"

  on_macos do
    url "https://github.com/caarlos0/org-stats/releases/download/v1.9.0/org-stats_darwin_all.tar.gz"
    sha256 "71ddf8ee19de07684ee8e6b8a209f1d914ad96e473bd7d99091da2e92bbac6f8"

    def install
      bin.install "org-stats"
      bash_completion.install "completions/org-stats.bash" => "org-stats"
      zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
      fish_completion.install "completions/org-stats.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.9.0/org-stats_linux_amd64.tar.gz"
      sha256 "7506980e0bffd3e71a18136a9e92f4fedd6b47466c3ea8605965143d338cff23"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/org-stats/releases/download/v1.9.0/org-stats_linux_arm64.tar.gz"
      sha256 "f89db19b9a96158d5d182dbeaf6d3d383aba6b4e92b77a722bb5fe99d96ec727"

      def install
        bin.install "org-stats"
        bash_completion.install "completions/org-stats.bash" => "org-stats"
        zsh_completion.install "completions/org-stats.zsh" => "_org-stats"
        fish_completion.install "completions/org-stats.fish"
      end
    end
  end
end
