# This file was generated by GoReleaser. DO NOT EDIT.
class Shcheck < Formula
  desc ""
  homepage ""
  version "0.5.0"

  if OS.mac?
    url "https://github.com/caarlos0/shcheck/releases/download/v0.5.0/shcheck_Darwin_x86_64.tar.gz"
    sha256 "df32c69f2dc618fb7e8776f81b35ac22f53165b903df29381b242b9646ea2a7e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/shcheck/releases/download/v0.5.0/shcheck_Linux_x86_64.tar.gz"
      sha256 "7916bf2661b05d4cfa8a246701ff2413e086eda4f1fc0096b6325f5ce9b06cba"
    end
  end

  def install
    bin.install "shcheck"
  end
end
