# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeedtestExporter < Formula
  desc "Exports Speedtest results to the Prometheus format"
  homepage ""
  version "0.3.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.3.1/speedtest-exporter_darwin_amd64.tar.gz"
    sha256 "d7b7ede7fa71a20b0dd6fb9228a1f66fc8d7847b800c42639014f03c1d0d0b2a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.3.1/speedtest-exporter_darwin_arm64.tar.gz"
    sha256 "fd13859a2c9010f75df630c80f704fa6c1a2715e0ae401d160d524985da63ed5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.3.1/speedtest-exporter_linux_amd64.tar.gz"
    sha256 "b1550e123b772554f126d5547e1dedbe8a0ac38abaee83ee306eeb2c0dc55f5a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.3.1/speedtest-exporter_linux_arm64.tar.gz"
    sha256 "dfecd500ac2fca2f1302da2045968966c4a061ed7b7f1e9b92d0a172de78b0ec"
  end

  depends_on "speedtest"

  def install
    bin.install "speedtest-exporter"
  end
end
