# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeedtestExporter < Formula
  desc "Exports Speedtest results to the Prometheus format"
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.1.0/speedtest-exporter_darwin_amd64.tar.gz"
    sha256 "b45e77b1969827770ddeeda5ff4de59a2347135ce4634bdbbe3750e49960666c"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.1.0/speedtest-exporter_darwin_arm64.tar.gz"
    sha256 "0b9d25a9c1496fb28f04496a29d48e11b97160951f8378a0775ab51bbb7c1b27"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.1.0/speedtest-exporter_linux_amd64.tar.gz"
    sha256 "b19552ab24745a4f3e767386481da92ff8c0d71d19bb5d4ebd41fb7eec015333"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/speedtest-exporter/releases/download/v0.1.0/speedtest-exporter_linux_arm64.tar.gz"
    sha256 "e4af7680971b9ddf2a495ee7eb16fc91eb6c9a15fde5b8dd63ccdb445c1a17a2"
  end

  def install
    bin.install "speedtest-exporter"
  end
end
