# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svu < Formula
  desc "Semantic Version Utility"
  homepage "https://github.com/caarlos0/svu"
  version "2.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/caarlos0/svu/releases/download/v2.1.0/svu_2.1.0_darwin_all.tar.gz"
    sha256 "c472b9ebce558f4a2275ac4e116a63e38245dbab35c9dd1e19a8dafe465e6c91"

    def install
      bin.install "svu"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/svu/releases/download/v2.1.0/svu_2.1.0_linux_amd64.tar.gz"
        sha256 "d5f1f92e3c0885567be44c85bcc978a8859405d7df5c4859217227bdec5df775"

        def install
          bin.install "svu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/svu/releases/download/v2.1.0/svu_2.1.0_linux_arm64.tar.gz"
        sha256 "386dbb29e58ee7e6dd67c4e043fbae4c46828c791596fa318f23c49416cadb27"

        def install
          bin.install "svu"
        end
      end
    end
  end
end
