# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Test < Formula
  desc ""
  homepage ""
  version "27.1.2"
  bottle :unneeded

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.2/test_27.1.2_darwin_all"
    sha256 "8e1e9764d7e8927c0199b323b185b72a601fe922d2834caeb0a592f6fafc6700"

    def install
      bin.install "test_27.1.2_darwin_all" => "test"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.2/test_27.1.2_linux_arm64"
      sha256 "797f93a018f3fd2db9ea78b90f002685840154a750a0a891055b89363e7b7275"

      def install
        bin.install "test_27.1.2_linux_arm64" => "test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.2/test_27.1.2_linux_amd64"
      sha256 "bbbf74a089d0b3af37eae5125b2310031f9b6774370a53fdce0b7e9bc1e17ae1"

      def install
        bin.install "test_27.1.2_linux_amd64" => "test"
      end
    end
  end

  def caveats; <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
  end
end
