# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timer < Formula
  desc "Timer is like sleep, but reports progress."
  homepage "https://github.com/caarlos0/timer"
  version "1.4.2"
  license "MIT"

  on_macos do
    url "https://github.com/caarlos0/timer/releases/download/v1.4.2/timer_darwin_all.tar.gz"
    sha256 "d3a6af01f18a2956638d1ee43fc8b4309a5874659d6d60ffcbfb1c010d824b4f"

    def install
      bin.install "timer"
      bash_completion.install "completions/timer.bash" => "timer"
      zsh_completion.install "completions/timer.zsh" => "_timer"
      fish_completion.install "completions/timer.fish"
      man1.install "manpages/timer.1.gz"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/timer/releases/download/v1.4.2/timer_linux_amd64.tar.gz"
        sha256 "3ddf3e794ba769eae24c2fdae2f300be751b33eb1eae359254304dc0c8b48859"

        def install
          bin.install "timer"
          bash_completion.install "completions/timer.bash" => "timer"
          zsh_completion.install "completions/timer.zsh" => "_timer"
          fish_completion.install "completions/timer.fish"
          man1.install "manpages/timer.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caarlos0/timer/releases/download/v1.4.2/timer_linux_arm64.tar.gz"
        sha256 "2501d7872545ad48bcee543eb9cd4cb3bf96efe6c13a874c074a76e799afbd45"

        def install
          bin.install "timer"
          bash_completion.install "completions/timer.bash" => "timer"
          zsh_completion.install "completions/timer.zsh" => "_timer"
          fish_completion.install "completions/timer.fish"
          man1.install "manpages/timer.1.gz"
        end
      end
    end
  end
end
