# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timer < Formula
  desc "Timer is like sleep, but reports progress."
  homepage "https://github.com/caarlos0/timer"
  version "1.2.0"

  on_macos do
    url "https://github.com/caarlos0/timer/releases/download/v1.2.0/timer_darwin_all.tar.gz"
    sha256 "b92fb448688f74240691389751dccab840acbe2a5f88135af221a99080fec280"

    def install
      bin.install "timer"
      bash_completion.install "completions/timer.bash" => "timer"
      zsh_completion.install "completions/timer.zsh" => "_timer"
      fish_completion.install "completions/timer.fish"
      man1.install "manpages/timer.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/timer/releases/download/v1.2.0/timer_linux_arm64.tar.gz"
      sha256 "7a103e9ddc179e9f34b5e0691f1be087372c910ff8f1528efaa9bd51110e71be"

      def install
        bin.install "timer"
        bash_completion.install "completions/timer.bash" => "timer"
        zsh_completion.install "completions/timer.zsh" => "_timer"
        fish_completion.install "completions/timer.fish"
        man1.install "manpages/timer.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/timer/releases/download/v1.2.0/timer_linux_amd64.tar.gz"
      sha256 "c0098453827ae71c1e4a044191bfc69a24ea74ad80b6b0de74180a63eb67d4e2"

      def install
        bin.install "timer"
        bash_completion.install "completions/timer.bash" => "timer"
        zsh_completion.install "completions/timer.zsh" => "_timer"
        fish_completion.install "completions/timer.fish"
        man1.install "manpages/timer.1.gz"
      end
    end
  end
end
