# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc "Task Timer (tt) is a dead simple TUI task timer"
  homepage "https://github.com/caarlos0/tasktimer"
  version "1.9.1"

  on_macos do
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.9.1/tt_darwin_all.tar.gz"
    sha256 "0384325a438e351a715b2278d7733463c57a46a595dbdf63d917de2cc6d8b025"

    def install
      bin.install "tt"
      bash_completion.install "completions/tt.bash" => "tt"
      zsh_completion.install "completions/tt.zsh" => "_tt"
      fish_completion.install "completions/tt.fish"
      man1.install "manpages/tt.1.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/tasktimer/releases/download/v1.9.1/tt_linux_arm64.tar.gz"
      sha256 "50c97bee7fe2b51f1fbc74eba4914eeaae5014b87e23888fed31a599f7cd88f2"

      def install
        bin.install "tt"
        bash_completion.install "completions/tt.bash" => "tt"
        zsh_completion.install "completions/tt.zsh" => "_tt"
        fish_completion.install "completions/tt.fish"
        man1.install "manpages/tt.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/tasktimer/releases/download/v1.9.1/tt_linux_amd64.tar.gz"
      sha256 "c242e99709298282ecbf923e2f30578638560d8029f4830e55b607251e3e6327"

      def install
        bin.install "tt"
        bash_completion.install "completions/tt.bash" => "tt"
        zsh_completion.install "completions/tt.zsh" => "_tt"
        fish_completion.install "completions/tt.fish"
        man1.install "manpages/tt.1.gz"
      end
    end
  end
end
