# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc "Task Timer (tt) is a dead simple TUI task timer."
  homepage "https://github.com/caarlos0/tasktimer"
  version "1.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.3/tt_darwin_amd64.tar.gz"
    sha256 "97aa0c841cfce8aca399384b70d69e03ee9b962c60c23d15f5d6db207f3f8a05"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.3/tt_linux_amd64.tar.gz"
    sha256 "af2a4c0ebefddf4d901a3fdbc8d575aecc7a2b34e01605bee9af9d23a2c04fa5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.3/tt_linux_arm64.tar.gz"
    sha256 "5455e7093084e68a7a3a4b9225701fe2f86b1a6b9289de7f47a4f9d55ca03985"
  end

  def install
    bin.install "tt"
    bash_completion.install "completions/tt.bash" => "tt"
    zsh_completion.install "completions/tt.zsh" => "_tt"
    fish_completion.install "completions/tt.fish"
  end
end
