# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tt < Formula
  desc "Task Timer (tt) is a dead simple TUI task timer."
  homepage "https://github.com/caarlos0/tasktimer"
  version "1.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.2/tt_darwin_amd64.tar.gz"
    sha256 "89ebaa4c714233fd3e26c499667854845d8992b1161c29820d3dcf9b656787b8"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.2/tt_linux_amd64.tar.gz"
    sha256 "df18a27f23abfde130652e10f66342c98c67af0cf7cec835173849608e91402b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/caarlos0/tasktimer/releases/download/v1.1.2/tt_linux_arm64.tar.gz"
    sha256 "f1f55a571c14bad9202b93db3dd72a5156446c390c89cc0c5c6bfffe74d46a4d"
  end

  def install
    bin.install "tt"
    bash_completion.install "completions/tt.bash" => "tt"
    zsh_completion.install "completions/tt.zsh" => "_tt"
    fish_completion.install "completions/tt.fish"
  end
end
