# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwitterCleaner < Formula
  desc "Automatically delete tweets, retweets, and favorites from your timeline, and, if provided, from your twitter archive as well"
  homepage "https://github.com/caarlos0/twitter-cleaner"
  version "0.5.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/twitter-cleaner/releases/download/v0.5.2/twitter-cleaner_0.5.2_darwin_amd64.tar.gz"
      sha256 "a4ac052c0e8b179852406cc68c2ebcb0282f0f810d1ae697aec9641541c89b67"
    end
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/twitter-cleaner/releases/download/v0.5.2/twitter-cleaner_0.5.2_darwin_arm64.tar.gz"
      sha256 "65fa296f53a0d0dc6662d72afdc34bc1f99152418e7d485c8a2446b108a231da"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/twitter-cleaner/releases/download/v0.5.2/twitter-cleaner_0.5.2_linux_amd64.tar.gz"
      sha256 "c23007f140c5008c44c01c44145aae11732275261495f536570a520321149400"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/twitter-cleaner/releases/download/v0.5.2/twitter-cleaner_0.5.2_linux_arm64.tar.gz"
      sha256 "6dec3c4681a151e9f6f8e7075738f5f1e4d52607a9584e5f5769b08bca52108f"
    end
  end

  def install
    bin.install "twitter-cleaner"
  end
end
