# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwitterWatcher < Formula
  desc "Creates a CSV file with all the watchers of your twitter account."
  homepage "https://github.com/caarlos0/twitter-watcher"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/twitter-watcher/releases/download/v0.1.0/twitter-watcher_0.1.0_darwin_arm64.tar.gz"
      sha256 "fdcdc3a051636218ea0462521f48bfb54b11bae2c62ce1306861bcaa963c8d80"

      def install
        bin.install "twitter-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/twitter-watcher/releases/download/v0.1.0/twitter-watcher_0.1.0_darwin_amd64.tar.gz"
      sha256 "70a718d2c5566203bd70557ee47a2f6bdfc571bba790e72e09a43323d1510d33"

      def install
        bin.install "twitter-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/twitter-watcher/releases/download/v0.1.0/twitter-watcher_0.1.0_linux_arm64.tar.gz"
      sha256 "04a72352b09f298cc6762a355ba3081269c88082f0bc79a0245e04c11f9b2a06"

      def install
        bin.install "twitter-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/twitter-watcher/releases/download/v0.1.0/twitter-watcher_0.1.0_linux_amd64.tar.gz"
      sha256 "ca95b262a8bb07fe4de766ab1b5f4fc4413cf75576da35077f521e4ca308ee66"

      def install
        bin.install "twitter-watcher"
      end
    end
  end
end
