# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VersionExporter < Formula
  desc "Exports the expiration time of your domains in the Prometheus format."
  homepage "https://github.com/caarlos0/version_exporter"
  version "1.2.0"

  on_macos do
    url "https://github.com/caarlos0/version_exporter/releases/download/v1.2.0/version_exporter_1.2.0_darwin_all.tar.gz"
    sha256 "eea9e0ae6c67a4e97db4dcadc0c92094de0f3262d142f9aecc4cc20d2b72e495"

    def install
      bin.install "version_exporter"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/version_exporter/releases/download/v1.2.0/version_exporter_1.2.0_linux_arm64.tar.gz"
      sha256 "43d3ec87f6175e123ee31e546362f989f6f084dafaf3f70dd5e7dedb2c1b8e87"

      def install
        bin.install "version_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/version_exporter/releases/download/v1.2.0/version_exporter_1.2.0_linux_amd64.tar.gz"
      sha256 "e65b39db857c922b299f4bd161dc57f9e15d5d47ea080b557b7f4925f7fd1661"

      def install
        bin.install "version_exporter"
      end
    end
  end
end
