# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XdgOpenSvc < Formula
  desc "Service to open URLs"
  homepage "https://caarlos0.dev"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.0/xdg-open-svc_0.1.0_darwin_arm64.tar.gz"
      sha256 "3cb20d7101987e5b750b8097661c8d800992ac0829176edc9ebdb101ed6d4708"

      def install
        bin.install "xdg-open-svc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.0/xdg-open-svc_0.1.0_darwin_amd64.tar.gz"
      sha256 "7b534e479213405f46c2d1188e38415a0ef9af3cc85ffe830c0cb7a19294cf6c"

      def install
        bin.install "xdg-open-svc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.0/xdg-open-svc_0.1.0_linux_arm64.tar.gz"
      sha256 "1dc7a01d6a764f0f980ea5c34cb02439c18ca0849394cc3d1fe43422c0c92df2"

      def install
        bin.install "xdg-open-svc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.0/xdg-open-svc_0.1.0_linux_amd64.tar.gz"
      sha256 "f547b5c9794fbcee8c1527cf70a64b503a16a83c87c44c5d83f3e68f546753d1"

      def install
        bin.install "xdg-open-svc"
      end
    end
  end

  service do
    run [opt_bin/"xdg-open-svc"]
    keep_alive true
    log_path var/"log/xdg-open-svc.log"
    error_log_path var/"log/xdg-open-svc.log"
  end
end
