# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XdgOpenSvc < Formula
  desc "Service to open URLs"
  homepage "https://caarlos0.dev"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.1/xdg-open-svc_0.1.1_darwin_arm64.tar.gz"
      sha256 "8ae28696bbc6cd2b4a02ee5150c7e9546030a254661ef884c939ca83057bbabe"

      def install
        bin.install "xdg-open-svc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.1/xdg-open-svc_0.1.1_darwin_amd64.tar.gz"
      sha256 "2da2891686598f1bd383437270d3861e2957c499fc3cfd3c7caa607d13857879"

      def install
        bin.install "xdg-open-svc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.1/xdg-open-svc_0.1.1_linux_arm64.tar.gz"
      sha256 "4d9056f0243fd74dfecdf50e871da17ca28fcdb6c03cb6e40ae72256b0ec6b0e"

      def install
        bin.install "xdg-open-svc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0/xdg-open-svc/releases/download/v0.1.1/xdg-open-svc_0.1.1_linux_amd64.tar.gz"
      sha256 "c9cc15f96b9474e190fe013f0526f84899ecffec400d53d4eefba16b00598327"

      def install
        bin.install "xdg-open-svc"
      end
    end
  end

  service do
    run [opt_bin/"xdg-open-svc"]
    keep_alive true
    log_path var/"log/xdg-open-svc.log"
    error_log_path var/"log/xdg-open-svc.log"
  end
end
